from __future__ import annotations

from collections import Counter
from typing import Any


def _build_task_register_catalog(max_count: int = 12) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for index in range(max_count):
        task_no = index + 1
        base = 30 + index * 10
        rows.extend([
            {
                "id": f"holding.task{index}_start_month",
                "name": f"任务 {task_no} 开始月份",
                "group": "task",
                "functionCode": [3],
                "area": "holding_register",
                "address": base,
                "wordLength": 1,
                "dataType": "uint16",
                "unit": "",
                "readable": True,
                "writable": False,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].StartTime.month",
                "notes": "StartTime 由下位机拆成月/日/时/分四个寄存器。",
            },
            {
                "id": f"holding.task{index}_start_day",
                "name": f"任务 {task_no} 开始日期",
                "group": "task",
                "functionCode": [3],
                "area": "holding_register",
                "address": base + 1,
                "wordLength": 1,
                "dataType": "uint16",
                "unit": "",
                "readable": True,
                "writable": False,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].StartTime.day",
                "notes": "",
            },
            {
                "id": f"holding.task{index}_start_hour",
                "name": f"任务 {task_no} 开始小时",
                "group": "task",
                "functionCode": [3],
                "area": "holding_register",
                "address": base + 2,
                "wordLength": 1,
                "dataType": "uint16",
                "unit": "",
                "readable": True,
                "writable": False,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].StartTime.hour",
                "notes": "",
            },
            {
                "id": f"holding.task{index}_start_minute",
                "name": f"任务 {task_no} 开始分钟",
                "group": "task",
                "functionCode": [3],
                "area": "holding_register",
                "address": base + 3,
                "wordLength": 1,
                "dataType": "uint16",
                "unit": "",
                "readable": True,
                "writable": False,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].StartTime.minute",
                "notes": "",
            },
            {
                "id": f"holding.task{index}_delay",
                "name": f"任务 {task_no} 持续时间",
                "group": "task",
                "functionCode": [3, 6, 16],
                "area": "holding_register",
                "address": base + 4,
                "addressEnd": base + 5,
                "wordLength": 2,
                "dataType": "uint32",
                "unit": "秒",
                "readable": True,
                "writable": True,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].delay",
                "notes": "高低 16 位合并显示。",
            },
            {
                "id": f"holding.task{index}_humidity_high",
                "name": f"任务 {task_no} 湿度高阈值",
                "group": "task",
                "functionCode": [3, 6, 16],
                "area": "holding_register",
                "address": base + 6,
                "wordLength": 1,
                "dataType": "int16",
                "unit": "%",
                "readable": True,
                "writable": True,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].HumidityValue.HThreshold",
                "notes": "",
            },
            {
                "id": f"holding.task{index}_humidity_low",
                "name": f"任务 {task_no} 湿度低阈值",
                "group": "task",
                "functionCode": [3, 6, 16],
                "area": "holding_register",
                "address": base + 7,
                "wordLength": 1,
                "dataType": "int16",
                "unit": "%",
                "readable": True,
                "writable": True,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].HumidityValue.LThreshold",
                "notes": "",
            },
            {
                "id": f"holding.task{index}_respiratory_on",
                "name": f"任务 {task_no} 呼吸加热开启阈值",
                "group": "task",
                "functionCode": [3, 6, 16],
                "area": "holding_register",
                "address": base + 8,
                "wordLength": 1,
                "dataType": "int16",
                "unit": "L/min",
                "readable": True,
                "writable": True,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].RespiratoryRate.HeatOnThreshold",
                "notes": "",
            },
            {
                "id": f"holding.task{index}_respiratory_off",
                "name": f"任务 {task_no} 呼吸加热关闭阈值",
                "group": "task",
                "functionCode": [3, 6, 16],
                "area": "holding_register",
                "address": base + 9,
                "wordLength": 1,
                "dataType": "int16",
                "unit": "L/min",
                "readable": True,
                "writable": True,
                "derived": False,
                "pollGroup": "slow",
                "uiVisible": True,
                "analysisExport": True,
                "sourceOfTruth": "firmware",
                "configKey": f"TaskArray[{index}].RespiratoryRate.HeatOffThreshold",
                "notes": "",
            },
        ])
    return rows


REGISTER_CATALOG: list[dict[str, Any]] = [
    {
        "id": "coil.software_reset",
        "name": "软件复位",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 0,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "SoftwareReset",
        "notes": "写 1 后触发复位。",
    },
    {
        "id": "coil.manual_heat",
        "name": "手动加热",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 1,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "ManualHeat",
        "notes": "远程手动加热控制位。",
    },
    {
        "id": "coil.double_mode",
        "name": "单双管模式",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 2,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "doubleMode",
        "notes": "单双管运行模式。",
    },
    {
        "id": "coil.humidity_enable",
        "name": "使能温湿度传感器",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 3,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "HumidityValue.VSW",
        "notes": "湿度通道优先/使能。",
    },
    {
        "id": "coil.pressure_enable",
        "name": "使能压力传感器",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 4,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "PressureValue.VSW",
        "notes": "压力通道优先/使能。",
    },
    {
        "id": "coil.respiratory_enable",
        "name": "使能呼吸传感器",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 5,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.VSW",
        "notes": "呼吸通道优先/使能。",
    },
    {
        "id": "coil.htc1_online",
        "name": "使能通道一在线监测",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 6,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "outOnline.HeatChannel1_Online",
        "notes": "固件 jsonCoilsMap 地址 0x06。",
    },
    {
        "id": "coil.htc2_online",
        "name": "使能通道二在线监测",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 7,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "outOnline.HeatChannel2_Online",
        "notes": "固件 jsonCoilsMap 地址 0x07。",
    },
    {
        "id": "coil.valve_online",
        "name": "使能阀门在线监测",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 8,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "outOnline.Valve_Online",
        "notes": "固件 jsonCoilsMap 地址 0x08。",
    },
    {
        "id": "coil.antifreeze_online",
        "name": "使能防冻在线监测",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 9,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "outOnline.Antifreeze_Online",
        "notes": "固件 jsonCoilsMap 地址 0x09。",
    },
    {
        "id": "coil.alarm_output_online",
        "name": "使能报警输出在线监测",
        "group": "control",
        "functionCode": [1, 5, 15],
        "area": "coil",
        "address": 10,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "configKey": "outOnline.AlarmOutput_Online",
        "notes": "固件 jsonCoilsMap 地址 0x0A。",
    },
    {
        "id": "input.total_heating",
        "name": "总加热状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 0,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": False,
        "sourceOfTruth": "firmware",
        "notes": "HTC1/HTC2 任一加热时为真。",
    },
    {
        "id": "input.total_alarm",
        "name": "总报警状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 4,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "关键告警汇总位。",
    },
    {
        "id": "input.humidity_alarm",
        "name": "温湿度传感器报警",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 5,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input.pressure_alarm",
        "name": "压力传感器报警",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 6,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input.heater_alarm",
        "name": "加热器报警",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 7,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "多加热相关错误汇总。",
    },
    {
        "id": "input.block_alarm",
        "name": "阻塞报警",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 8,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input.exhale_state",
        "name": "呼气状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 9,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "包含正常呼气和低流速告警。",
    },
    {
        "id": "input.inhale_state",
        "name": "吸气状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 10,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "包含正常吸气和高流速告警。",
    },
    {
        "id": "input.htc1_state",
        "name": "通道一加热状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 11,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input.htc2_state",
        "name": "通道二加热状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 12,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input.valve_state",
        "name": "阀门状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 13,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "固件 GetDeviceState(VALVE)。",
    },
    {
        "id": "input.antifreeze_state",
        "name": "防冻状态",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 14,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "固件 GetDeviceState(ANTIFREEZE)。",
    },
    {
        "id": "input.breath_sensor_alarm",
        "name": "呼吸传感器报警",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 15,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input.humidity_high_alarm",
        "name": "湿度过高报警",
        "group": "status",
        "functionCode": [2],
        "area": "discrete_input",
        "address": 16,
        "wordLength": 1,
        "dataType": "bool",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "holding.double_switch",
        "name": "切换频率",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 0,
        "wordLength": 1,
        "dataType": "uint16",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": ".doubleSwitch.",
        "notes": "当前分析系统界面名更接近最小保护时间。",
    },
    {
        "id": "holding.humidity_high",
        "name": "湿度高阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 1,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "%",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "HumidityValue.HThreshold",
        "notes": "",
    },
    {
        "id": "holding.humidity_low",
        "name": "湿度低阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 2,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "%",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "HumidityValue.LThreshold",
        "notes": "",
    },
    {
        "id": "holding.temperature_high",
        "name": "温度高阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 3,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "°C",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "Temperature.HThreshold",
        "notes": "",
    },
    {
        "id": "holding.temperature_low",
        "name": "温度低阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 4,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "°C",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "Temperature.LThreshold",
        "notes": "",
    },
    {
        "id": "holding.temperature_delay",
        "name": "辅热加热时长",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 5,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "Temperature.delay",
        "notes": "协议文档叫辅热加热时长，固件配置键是 Temperature.delay。",
    },
    {
        "id": "holding.pressure_high",
        "name": "正压力报警阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 6,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "kPa",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "PressureValue.HThreshold",
        "notes": "",
    },
    {
        "id": "holding.pressure_low",
        "name": "负压力报警阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 7,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "kPa",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "PressureValue.LThreshold",
        "notes": "",
    },
    {
        "id": "holding.respiratory_high",
        "name": "呼吸加热开启阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 8,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "L/min",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.HeatOnThreshold",
        "notes": "固件地址 8 对应 HeatOnThreshold。",
    },
    {
        "id": "holding.respiratory_low",
        "name": "呼吸加热关闭阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 9,
        "wordLength": 1,
        "dataType": "int16",
        "unit": "L/min",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.HeatOffThreshold",
        "notes": "固件地址 9 对应 HeatOffThreshold。",
    },
    {
        "id": "holding.exhale_timeout_min_sec",
        "name": "呼气超时最小秒数",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 10,
        "wordLength": 1,
        "dataType": "uint16",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.ExhaleTimeoutMinSec",
        "notes": "固件 jsonRegisterMap 地址 10。",
    },
    {
        "id": "holding.no_change_alarm_time_sec",
        "name": "呼吸无变化告警时间",
        "group": "config",
        "functionCode": [3, 16],
        "area": "holding_register",
        "address": 11,
        "addressEnd": 12,
        "wordLength": 2,
        "dataType": "uint32",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.NoChangeAlarmTimeSec",
        "notes": "固件 jsonRegisterMap 地址 11-12，高字在前。",
    },
    {
        "id": "holding.exhale_timeout_sec",
        "name": "呼气超时秒数",
        "group": "config",
        "functionCode": [3, 16],
        "area": "holding_register",
        "address": 13,
        "addressEnd": 14,
        "wordLength": 2,
        "dataType": "uint32",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.ExhaleTimeoutSec",
        "notes": "固件 jsonRegisterMap 地址 13-14，高字在前。",
    },
    {
        "id": "holding.heat_evidence_interval_sec",
        "name": "呼吸热证据间隔",
        "group": "config",
        "functionCode": [3, 16],
        "area": "holding_register",
        "address": 15,
        "addressEnd": 16,
        "wordLength": 2,
        "dataType": "uint32",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.HeatEvidenceIntervalSec",
        "notes": "固件 jsonRegisterMap 地址 15-16，高字在前。",
    },
    {
        "id": "holding.heat_evidence_count",
        "name": "呼吸热证据计数",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 17,
        "wordLength": 1,
        "dataType": "uint16",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.HeatEvidenceCount",
        "notes": "固件 jsonRegisterMap 地址 17。",
    },
    {
        "id": "holding.humidity_offset",
        "name": "湿度偏移",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 18,
        "addressEnd": 19,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "%",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "HumidityValue.offset",
        "notes": "固件 jsonRegisterMap 地址 18-19，高字在前。",
    },
    {
        "id": "holding.respiratory_offset",
        "name": "呼吸流量偏移",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 20,
        "addressEnd": 21,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "L/min",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.offset",
        "notes": "固件 jsonRegisterMap 地址 20-21，高字在前。",
    },
    {
        "id": "holding.slave_address",
        "name": "设备地址",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 22,
        "wordLength": 1,
        "dataType": "uint16",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "uartInfor.addr",
        "notes": "写入后需刷新当前设备档案。",
    },
    {
        "id": "holding.derange_lt",
        "name": "有效出气分区阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 23,
        "addressEnd": 24,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "L/min",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.DERangeLT",
        "notes": "",
    },
    {
        "id": "holding.derange_ht",
        "name": "有效吸气分区阈值",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 25,
        "addressEnd": 26,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "L/min",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "RespiratoryRate.DERangeHT",
        "notes": "",
    },
    {
        "id": "holding.task_count",
        "name": "任务数量",
        "group": "config",
        "functionCode": [3],
        "area": "holding_register",
        "address": 27,
        "wordLength": 1,
        "dataType": "uint16",
        "unit": "",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "TaskCount",
        "notes": "下位机当前启用的任务数量。",
    },
    {
        "id": "holding.humidity_heat_evidence_interval_sec",
        "name": "湿度热证据间隔",
        "group": "config",
        "functionCode": [3, 16],
        "area": "holding_register",
        "address": 150,
        "addressEnd": 151,
        "wordLength": 2,
        "dataType": "uint32",
        "unit": "秒",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "HumidityValue.HeatEvidenceIntervalSec",
        "notes": "固件 jsonRegisterMap 地址 150-151，高字在前。",
    },
    {
        "id": "holding.humidity_heat_evidence_count",
        "name": "湿度热证据计数",
        "group": "config",
        "functionCode": [3, 6, 16],
        "area": "holding_register",
        "address": 152,
        "wordLength": 1,
        "dataType": "uint16",
        "unit": "",
        "readable": True,
        "writable": True,
        "derived": False,
        "pollGroup": "slow",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "configKey": "HumidityValue.HeatEvidenceCount",
        "notes": "固件 jsonRegisterMap 地址 152。",
    },
    {
        "id": "input_register.temperature",
        "name": "温度",
        "group": "analog",
        "functionCode": [4],
        "area": "input_register",
        "address": 2,
        "addressEnd": 3,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "°C",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input_register.humidity",
        "name": "湿度",
        "group": "analog",
        "functionCode": [4],
        "area": "input_register",
        "address": 4,
        "addressEnd": 5,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "%",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input_register.pressure",
        "name": "压力",
        "group": "analog",
        "functionCode": [4],
        "area": "input_register",
        "address": 6,
        "addressEnd": 7,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "kPa",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "standard",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
    {
        "id": "input_register.flow",
        "name": "呼吸流速",
        "group": "analog",
        "functionCode": [4],
        "area": "input_register",
        "address": 8,
        "addressEnd": 9,
        "wordLength": 2,
        "dataType": "float32",
        "unit": "L/min",
        "readable": True,
        "writable": False,
        "derived": False,
        "pollGroup": "fast",
        "uiVisible": True,
        "analysisExport": True,
        "sourceOfTruth": "firmware",
        "notes": "",
    },
]

REGISTER_CATALOG.extend(_build_task_register_catalog())


def get_register_catalog() -> list[dict[str, Any]]:
    return [dict(item) for item in REGISTER_CATALOG]


def get_register_catalog_summary() -> dict[str, Any]:
    group_counts = Counter(item["group"] for item in REGISTER_CATALOG)
    area_counts = Counter(item["area"] for item in REGISTER_CATALOG)
    writable_count = sum(1 for item in REGISTER_CATALOG if item.get("writable"))
    readable_count = sum(1 for item in REGISTER_CATALOG if item.get("readable"))
    return {
        "total": len(REGISTER_CATALOG),
        "readable": readable_count,
        "writable": writable_count,
        "groups": dict(group_counts),
        "areas": dict(area_counts),
    }
